### ISSUE TITLE
[BUG] Casual Rank

### ISSUE THREAD

**Issue by barbiehunter** [Hypnootize/Sunset-Hud#1]
At the end of a casual round the casual level is bugged.
Resolution: 16:9, 1920 x 1080
![20190827172540_1](https://user-images.githubusercontent.com/38357837/63974728-b6690680-caad-11e9-9c14-a0c53d768665.jpg)

**Comment by Hypnootize** [comment]
Yeah I was aware of that, but the thing is i can't fix this without changing the way it looks in the main menu as well and i rather have it look good in the menu.

It used to be possible to control it with the "if_mini" option but since the last main update it doesn't work anymore for the font, lets hope valve does something about it.
