### ISSUE TITLE
Causal rank for other players?

### ISSUE THREAD

**Issue by yeajustwannaplay** [Hypnootize/Sunset-Hud#2]
I want to see other people ranks in causal but nothing works. I’ve changed h scoreboard res and all of that but it still doesn’t work. Thanks.

**Comment by yeajustwannaplay** [comment]
oh, and the ctf bottom hud is not centred https://imgur.com/gallery/WDblmG2

**Comment by yeajustwannaplay** [comment]
and sorry for posting so much, i cant see the class model image while in game.

**Comment by Hypnootize** [comment]
I hided the medal badges since i don't really like having them in the scoreboard and so i could get more space for the player names.

I know the ctf arrows are not 100% centred all the time but i already wanna create some better ones as the current ones where pretty rushed. will see in the future.

I just tried and the class model works fine for me, check if you have cl_hud_playerclass_use_playermodel set to 1!

**Comment by yeajustwannaplay** [comment]
Alright thanks!
